restore evu date attribute correctly
BenPru/luxtronik pull request #283
Opened 2024-10-09 23:40 UTC by s-kurz

restore the evu dates attribute and solve the TypeError: 'datetime.time' issue 
fixes #249 
fixes #281

2024-10-25 07:40 UTC, Gifford47 commented
Can this PR already be merged?

2024-10-31 12:24 UTC, s-kurz commented
add min firmware version to the current power consumption sensor in alignment with the energy sensors min firmware 
fixes #277

2024-10-31 14:16 UTC, Gifford47 commented
In my case the attribute EVU_DAYS isn't set correctly. It's always "" (empty string). Does it works on your own?@s-kurz

2024-10-31 15:18 UTC, s-kurz commented
@Gifford47 Its similar for me. I just fixed the issue that came from the attribute restoration. To test this part I manually change the attributes and then did a restart, which does restored them correctly. I never checked the logic of how the dates are actually set, nor am I sure if they should be set for my setup

2024-10-31 16:37 UTC, Gifford47 commented
Ok, thanks for the info!
I'll test it the next days

2024-11-03 20:30 UTC, Gifford47 commented
@s-kurz can you have a closer look why the attribute "SA.EVU_DAYS" isn't set correctly? I didn't find the bug yet...

2024-11-06 21:01 UTC, Gifford47 commented
Ok, basic logic works so far. The only problem is that only the current day will be saved into attribute. The other days before are removed when a new day is appended... I cannot find why
@s-kurz @BenPru could you have a look please?

2024-11-07 09:28 UTC, Gifford47 commented
@BenPru Please don´t merge yet, there's a smaller bug in the logic. I'll fix it in a few days.

2024-11-08 10:24 UTC, Gifford47 commented on custom_components/luxtronik/sensor.py
> +        if not isinstance(self._attr_cache[SA.EVU_DAYS], list):
here's a bug. it has the checked if the attribute is a string. if yes, convert it to a list to append a new weekday. Please replace with the following:

`
        if isinstance(self._attr_cache[SA.EVU_DAYS], str):
            self._attr_cache[SA.EVU_DAYS] = self._attr_cache[SA.EVU_DAYS].split(',')
        elif not isinstance(self._attr_cache[SA.EVU_DAYS], list):
            self._attr_cache[SA.EVU_DAYS] = list()		# failsafe
`

2024-11-08 10:25 UTC, Gifford47 requested changes
on line 399 is a bug. it has to be checked if the attribute is a string. if yes, convert it to a list to append a new weekday. Please replace with the following:

``` 
        if isinstance(self._attr_cache[SA.EVU_DAYS], str):
            self._attr_cache[SA.EVU_DAYS] = self._attr_cache[SA.EVU_DAYS].split(',')
        elif not isinstance(self._attr_cache[SA.EVU_DAYS], list):
            self._attr_cache[SA.EVU_DAYS] = list()		# failsafe
```

2024-11-08 19:56 UTC, s-kurz commented
@Gifford47 I made the change. But as I said I don't have a good way to test it since EVU is never active for me. I would propose we merge it at this state wether the evu dates are working now or not, so we at least fix the other more problematic issues with the disapperaing/unavailable sensors

2024-11-15 20:57 UTC, merged